var child = [
  { 'dupe': false, 'type': 8, 'name': 'handlers.js', 'dir': 'c0', 'linked': 5, 'url': 'http://10.0.2.2/kryptografia/js/handlers.js', 'fetched': true, 'code': 200, 'len': 650, 'decl_mime': 'application/x-javascript', 'sniff_mime': 'application/javascript', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 2, 0, 0, 0, 0 ], 'sig': 0xfff5871c },
  { 'dupe': false, 'type': 8, 'name': 'jquery-1.12.3.min.js', 'dir': 'c1', 'linked': 2, 'url': 'http://10.0.2.2/kryptografia/js/jquery-1.12.3.min.js', 'fetched': true, 'code': 200, 'len': 97180, 'decl_mime': 'application/x-javascript', 'sniff_mime': 'text/plain', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 2, 0, 0, 1, 0 ], 'sig': 0x43e46415 },
  { 'dupe': false, 'type': 8, 'name': 'mychat.js', 'dir': 'c2', 'linked': 2, 'url': 'http://10.0.2.2/kryptografia/js/mychat.js', 'fetched': true, 'code': 200, 'len': 1895, 'decl_mime': 'application/x-javascript', 'sniff_mime': 'application/javascript', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0xfff6d5cd },
  { 'dupe': true, 'type': 32, 'name': 'handlers.js.7z', 'dir': 'c3', 'linked': 0, 'url': 'http://10.0.2.2/kryptografia/js/handlers.js.7z', 'fetched': true, 'code': 404, 'len': 1147, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffdfffff },
  { 'dupe': true, 'type': 32, 'name': 'mychat.js.7z', 'dir': 'c112', 'linked': 0, 'url': 'http://10.0.2.2/kryptografia/js/mychat.js.7z', 'fetched': true, 'code': 404, 'len': 1147, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffdfffff },
  { 'dupe': false, 'type': 64, 'name': 'C=N', 'dir': 'c221', 'linked': 2, 'url': 'http://10.0.2.2/kryptografia/js/?C=N;O=D', 'fetched': true, 'code': 200, 'len': 1358, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'ISO-8859-1', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0x28f4fa31 },
  { 'dupe': false, 'type': 64, 'name': 'O=D', 'dir': 'c222', 'linked': 2, 'url': 'http://10.0.2.2/kryptografia/js/?C=N;O=D', 'fetched': true, 'code': 200, 'len': 1358, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'ISO-8859-1', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0x28f4fa31 }
];
